name: Deploy VPS de Prueba
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SSH_HOST }}
        username: ${{ secrets.DEV_SSH_USER }}
        key: ${{ secrets.DEV_SSH_KEY }}
        script: |
          source ~/.bashrc
          source ~/.bashrc
          export PATH=$PATH:/usr/local/bin
          node -v
          npm -v
          cd htdocs/titulacion.abimaelfv.site
          git pull origin main
          ls
          npm install
          npm run build
          ls
